config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors, controllers: {
    # sessions: 'users/sessions',
    registrations: 'doctors/registrations',
  }
  devise_for :patients, controllers: {
    # sessions: 'users/sessions',
    registrations: 'patients/registrations',
  }
  resources :users
  resources :solutions
  resources :cases
  resources :dashboards
  root to: 'dashboards#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
  belongs_to :patient, class_name: "Patient", foreign_key: "patient_id"
  belongs_to :doctor, class_name: "Doctor", foreign_key: "doctor_id", required: false

  scope :active, -> { where(status: 'active') }
  scope :closed, -> { where(status: 'closed') }
end

app/models/doctor.rb
class Doctor < User
end

app/models/patient.rb
class Patient < User
  has_many :cases, foreign_key: "patient_id"
  
  def active_case
    cases.where(status: 'active').take
  end

  def has_active_case?
    active_case.present?
  end
end

app/models/solution.rb
class Solution < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  enum type: [
    :Doctor,
    :Patient
  ]

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  devise_group :user, contains: [:patient, :doctor]
  before_action :authenticate_user!
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_case, only: [:show, :edit, :update, :destroy]

  def index
    @cases = Case.all
  end

  def show
  end

  def new
    @active_case = current_user.cases.where(status: 'active').take
    @closed_cases = current_user.cases.where(status: 'closed')
  end

  def create
    @case = Case.new(case_params)
    @case.patient_id = current_user.id
    @case.status = 'active'
    respond_to do |format|
      if @case.save
        format.html { redirect_to new_case_path, notice: 'Zgłoszenie zostało zapisane.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @case.update(case_params)
        # TODO refactor this
        if params["commit"] == "Aktualizuj i zamknij zgłoszenie"
          @case.update(doctor: current_user, status: 'closed')
        end

        format.html { redirect_to edit_case_path(@case), notice: 'Zgłoszenie zostało zaktualizowane.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    current_user.active_case.destroy
    redirect_to new_case_path
  end

  private
    def set_case
      @case = Case.find(params[:id])
    end

    def case_params
      params.require(:case).permit(:description, :solution, :specialist_type)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    if patient_signed_in?
      redirect_to new_case_path and return
    end
    @unassigned_cases = Case.active
  end
end

app/controllers/doctors/registrations_controller.rb
# frozen_string_literal: true
require "net/http"
require "uri"

class Doctors::RegistrationsController < Devise::RegistrationsController
  def create
    # This is a prototype of NIL API integration
    # formatted_dob = sign_up_params["dob"].gsub("-","")
    # pwz_number = sign_up_params["pwz_number"]
    #
    # url = "http://hdt.hipokrates.org/?pwz=#{pwz_number}&data_ur=#{formatted_dob}&format=json"
    # p url
    #
    # uri = URI.parse(url)
    # response = Net::HTTP.get_response(uri)
    # json_response = JSON.parse(response.body)
    # p json_response
    # pwz_verified = (json_response["wynik"] == "1")
    # unless true
    #   redirect_to new_registration_path(User, valid: false, user_type: sign_up_params["user_type"]) and return
    # end
    super
  end

  protected

  def sign_up_params
    params.require(:doctor).permit(:email, :password, :password_confirmation, :first_name, :last_name, :pesel, :address, :phone, :pwz_number, :dob, :age, :weight, :height, :sex)
  end

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/patients/registrations_controller.rb
# frozen_string_literal: true

class Patients::RegistrationsController < Devise::RegistrationsController

  protected

  def sign_up_params
    params.require(:patient).permit(:email, :password, :password_confirmation, :first_name, :last_name, :pesel, :address, :phone, :dob, :age, :weight, :height, :sex)
  end

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :set_solution, only: [:show, :edit, :update, :destroy]

  def create
    @solution = Solution.new(solution_params)

    respond_to do |format|
      if @solution.save
        format.html { redirect_to @solution, notice: 'Solution was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @solution.destroy
    respond_to do |format|
      format.html { redirect_to solutions_url, notice: 'Solution was successfully destroyed.' }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name, :pesel, :address, :phone, :pwz_number, :dob, :age, :weight, :height, :sex)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cases/_form.html.erb
<%= form_with model: patient_case, local: true do |form| %>
  <% if patient_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient_case.errors.count, "error") %> prohibited this patient_case from being saved:</h2>

      <ul>
      <% patient_case.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :solution %>
    <%= form.text_area :solution %>
  </div>

  <div class="field">
    <%= form.label :specialist_type %>
    <%= form.text_field :specialist_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cases/edit.html.erb
 <!-- Wrapper Start -->
 <div class="wrapper">
 <!-- Page Content  -->
 <div id="content-page" class="content-page">
    <!-- TOP Nav Bar -->
    <%= render partial: 'shared/top_navbar' %>
    <!-- TOP Nav Bar END -->
    <div class="container-fluid">
       <div class="row">
          <div class="col-lg-4 row m-0 p-0">
             <div class="col-sm-12">
             <div class="iq-card iq-card-block iq-card-stretch iq-user-profile-block">
                <div class="iq-card-body">
                   <div class="user-details-block">
                      <div class="user-profile text-center">
                         <%= image_tag @case.patient.sex == 'm' ? "user/09.jpg" : "user/15.jpg", class: 'rounded-circle img-fluid'%>
                      </div>
                      <div class="text-center mt-3">
                         <h4><b><%= @case.patient.full_name %></b></h4>
                         <p><%= ((Time.zone.now - @case.patient.dob.to_time) / 1.year.seconds).floor %> yo</p>
                      </div>
                      <ul class="doctoe-sedual d-flex align-items-center justify-content-between p-0 mt-4 mb-0">
                        <li class="text-center">
                           <h6 class="text-primary">Sex</h6>
                           <h3><%= @case.patient.sex.capitalize %></h3>
                        </li>
                         <li class="text-center">
                            <h6 class="text-primary">Weight</h6>
                            <h3><%= @case.patient.weight %><span>kg</span></h3>
                         </li>
                         <li class="text-center">
                            <h6 class="text-primary">Height</h6>
                            <h3><%= @case.patient.height %><span>cm</span></h3>
                         </li>
                      </ul>
                   </div>
                   <hr/>
                    <div class="patient-steps">
                       <div class="d-flex align-items-center justify-content-between">
                          <div class="col-md-12">
                            <div class="data-block">
                               <p class="mb-0">ID number</p>
                               <h5><%= @case.patient.pesel %></h5>
                            </div>
                            <div class="data-block">
                               <p class="mb-0">Phone</p>
                               <h5><%= @case.patient.phone %></h5>
                            </div>
                             <div class="data-block mt-3">
                                <p class="mb-0">Chronic Diseases</p>
                                <h5><%= @case.patient.chronic_diseases %></h5>
                             </div>
                          </div>
                       </div>
                    </div>
                </div>
             </div>
           </div>
          </div>
          <div class="col-lg-8">
             <div class="iq-card iq-card-block iq-card-stretch">
                <div class="iq-card-body pb-0">
                   <div class="row">
                      <div class="col-sm-12">
                         <div class="iq-card">
                            <div class="iq-header-title">
                               <h4 class="card-title text-primary">
                                 Case description
                                 <% if @case.status == 'closed' %>
                                   <span class="badge badge-danger">Closed (recommendations available for patient insight)</span>
                                 <% end %>
                               </h4>
                            </div>
                            <p class="mb-0">
                              <%= @case.description %>
                            </p>
                         </div>
                      </div>
                       <div class="col-sm-12">
                          <div class="iq-card">
                             <div class="iq-header-title">
                                <h4 class="card-title text-primary">Files</h4>
                             </div>
                             <p class="mb-0">
                               -
                             </p>
                          </div>
                       </div>
                       <% if @case.doctor.present? %>
                        <div class="col-sm-12">
                           <div class="iq-card">
                              <div class="iq-header-title">
                                 <h4 class="card-title text-primary">Recommendations</h4>
                              </div>
                              <div class="chat-content" style="height:unset; overflow-y:auto">
                                <div class="chat chat-left">
                                  <div class="chat-user">
                                    <a class="avatar m-0">
                                      <%= image_tag "user/12.jpg", class: 'avatar-35 rounded'%>
                                    </a>
                                      <span class="chat-time mt-1"><%= @case.doctor.first_name %><br/><%= @case.doctor.last_name %></span>
                                  </div>
                                  <div class="chat-detail">
                                    <div class="chat-message">
                                      <p><%= @case.solution %></p>
                                    </div>
                                  </div>
                                </div>
                              </div>
                           </div>
                        </div>
                        <% end %>
                   </div>
                </div>
             </div>
            <div class="iq-card iq-card-block iq-card-stretch">
               <div class="iq-card-body pb-0">

                <div class="row" style="margin-bottom: 15px">
                   <div class="col-md-12">
                      <div class="iq-header-title">
                         <h4 class="card-title text-primary">Recommendations</h4>
                      </div>
                     <%= form_with model: @case, local: true do |form| %>
                       <div class="field">
                         <%= form.text_area :solution, class: "form-control mb-3", placeholder: "Zalecenia lekarskie" %>
                       </div>
                        <!--
                       <div class="field">
                         <%= form.label :specialist_type %>
                         <%= form.text_field :specialist_type %>
                       </div>
                        -->
                       <div class="actions">
                         <%= form.submit 'Update case', class: "btn btn-block mb-3 btn-primary rounded-pill" %>
                       </div>
                       <div class="row">
                         <div class="col-md-4">
                           <button type="button" class="btn btn-block mb-3 btn-primary rounded-pill" data-toggle="modal" data-target="#callModal"><i class="ri-phone-fill"></i>Call</button>
                         </div>
                         <div class="col-md-4">
                           <button type="button" class="btn btn-block mb-3 btn-dark rounded-pill" data-toggle="modal" data-target="#specializationModal"><i class="ri-shield-cross-fill"></i>Assign specialist</button>
                         </div>
                         <div class="col-md-4">
                           <%= form.submit 'Update and close case', class: "btn btn-block mb-3 btn-success rounded-pill" %>
                         </div>
                       </div>
                     <% end %>
                   </div>
                  </div>
              </div>
             </div>
            <!-- <div class="iq-card iq-card-block iq-card-stretch">
               <div class="iq-card-body pb-0">
                  <div class="row">
                     <div class="col-sm-12">
                        <div class="iq-card">
                           <div class="iq-header-title">
                              <h4 class="card-title text-primary">Komentarze odnośnie pacjenta</h4>
                           </div>
                           <div class="form-group">
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="2"></textarea>
                           </div>
                           <button type="submit" class="btn btn-primary">Dodaj komentarz</button>
                           <div class="chat-content" style="height:unset; overflow-y:auto">
                             <div class="chat chat-left">
                               <div class="chat-user">
                                 <a class="avatar m-0">
                                   <%= image_tag "user/06.jpg", class: 'avatar-35 rounded'%>
                                 </a>
                                   <span class="chat-time mt-1">Imie<br/>Lekarza</span>
                               </div>
                               <div class="chat-detail">
                                 <div class="chat-message">
                                   <p>Pacjent odmówił dalszej diagnostyki nerek</p>
                                 </div>
                               </div>
                             </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div> -->
          </div>
       </div>
    </div>
    <!-- Footer -->
       <footer class="bg-white iq-footer">
          <div class="container-fluid">
             <div class="row">
                <div class="col-lg-6">
                   <ul class="list-inline mb-0">
                      <li class="list-inline-item"><a href="privacy-policy.html">Privacy Policy</a></li>
                      <li class="list-inline-item"><a href="terms-of-service.html">Terms of Service</a></li>
                   </ul>
                </div>
                <div class="col-lg-6 text-right">
                   Copyright 2020 <a href="#">OpenTelemedicine.com</a>
                </div>
             </div>
          </div>
       </footer>
       <!-- Footer END -->
 </div>
</div>


<!-- CALL MODAL -->
<!-- Modal -->
<div class="modal fade" id="callModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Calling... </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <center>
          <h4><%= @case.patient.full_name %></h4>
          <h3><%= @case.patient.phone %></h3>
          <p>Please remember that call time is limited to 10 minutes</p>
          <%= image_tag "web_call.png" %>
          <hr>
          <button type="button" class="btn btn-lg btn-danger" data-dismiss="modal">End call</button>
        </center>
      </div>
    </div>
  </div>
</div>

<!-- SPECIALIZATION MODAL -->
<!-- Modal -->
<div class="modal fade" id="specializationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Assign case specialization </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <center>
          <h4><%= @case.patient.full_name %></h4>
          <p>Request a specialist consult (Tagged patient questions will be prioritised on specialist's dashboard)</p>
          <select class="form-control" id="exampleFormControlSelect1">
            <option selected="" disabled="">Select specialist</option>
            <option>Endocrynology</option>
            <option>Dermatology</option>
            <option>Diabetology</option>
            <option>Psichiatry</option>
            <option>Oncology</option>
            <option>Nephrology</option>
         </select>
          <hr>
          <button type="button" class="btn btn-lg btn-success">Save</button>
          <button type="button" class="btn btn-lg btn-danger" data-dismiss="modal">Cancel</button>
        </center>
      </div>
    </div>
  </div>
</div>

app/views/cases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Przypadki</h1>

<table>
  <thead>
    <tr>
      <th>Opis</th>
      <th>Zalecenia</th>
      <th>Typ slecjalisty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cases.each do |case| %>
      <tr>
        <td><%= case.description %></td>
        <td><%= case.solution %></td>
        <td><%= case.specialist_type %></td>
        <td><%= link_to 'Pokaż', case %></td>
        <td><%= link_to 'Edytuj', edit_case_path(case) %></td>
        <td><%= link_to 'Usuń', case, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nowy przypadek', new_case_path %>

app/views/dashboards/show.html.erb
   <!-- Wrapper Start -->
   <div class="wrapper">
   <!-- Page Content  -->
   <div id="content-page" class="content-page">
      <!-- TOP Nav Bar -->
      <%= render partial: 'shared/top_navbar' %>
      <!-- TOP Nav Bar END -->
      <div class="container-fluid">
         <div class="row">
           <div class="col-sm-12">
              <div class="iq-card iq-card-block iq-card-stretch iq-card-height">
                <div class="iq-card-header d-flex justify-content-between">
                   <div class="iq-header-title">
                      <h4 class="card-title">Cases assigned to your specialization</h4>
                   </div>
                </div>
                <div class="iq-card-body">
                  <div class="d-inline-block text-center w-100">
                     <p>No cases currently assigned to your specialization</p>
                  </div>
                </div>
              </div>
             </div>
             <div class="col-sm-12">
                <div class="iq-card iq-card-block iq-card-stretch iq-card-height">
                  <div class="iq-card-header d-flex justify-content-between">
                     <div class="iq-header-title">
                        <h4 class="card-title">Not assigned cases</h4>
                     </div>
                  </div>
                  <div class="iq-card-body">
                     <div class="table-responsive">
                        <table class="table mb-0 table-borderless">
                           <thead>
                              <tr>
                                 <th scope="col">Patient</th>
                                 <th scope="col" style="width: 65%">Case</th>
                                 <th scope="col">Case submition date</th>
                              </tr>
                           </thead>
                           <tbody>
                             <% @unassigned_cases.each do |c| %>
                              <tr class="case-row">
                                 <td>
                                   <%= image_tag c.patient.sex == 'm' ? "user/09.jpg" : "user/1.jpg", class: "rounded-circle img-fluid avatar-40" %>
                                   <span style="white-space:nowrap"><%= c.patient.full_name %></span>
                                   <% if c.covid_suspected %>
                                     <span class="badge badge-danger">COVID-19 suspect</span>
                                   <% end %>
                                 </td>
                                 <td>
                                   <%= link_to edit_case_path(c) do %>
                                    <p style="font-size: 12px; color: #a09e9e">
                                      <%= c.description %>
                                    </p>
                                   <% end %>
                                 </td>
                                 <td><%= c.created_at.to_date %></td>
                              </tr>
                             <% end %>
                           </tbody>
                        </table>
                     </div>
                  </div>
                </div>
             </div>
         </div>
      </div>
      <!-- Footer -->
         <footer class="bg-white iq-footer">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-lg-6">
                     <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="privacy-policy.html">Privacy policy</a></li>
                        <li class="list-inline-item"><a href="terms-of-service.html">Terms of Service</a></li>
                     </ul>
                  </div>
                  <div class="col-lg-6 text-right">
                     Copyright 2020 <a href="#">OpenTelemedicine.com</a>
                  </div>
               </div>
            </div>
         </footer>
         <!-- Footer END -->
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenTelemedicine.com TheGlobalHack initiative</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>
  <body>
    <% if alert.present? %>
    <div class="alert alert-danger" role="alert">
      <div class="iq-alert-icon">
         <i class="ri-information-line"></i>
      </div>
      <div class="iq-alert-text"><%= alert %></div>
     </div>
     <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_top_navbar.html.erb
 <!-- TOP Nav Bar -->
 <div class="iq-top-navbar">
    <div class="iq-navbar-custom">
       <div class="iq-sidebar-logo">
          <div class="top-logo">
             <a href="index.html" class="logo">
             <img src="images/logo.png" class="img-fluid" alt="">
             <span>XRay</span>
             </a>
          </div>
       </div>
       <nav class="navbar navbar-expand-lg navbar-light p-0">
          <% if doctor_signed_in? %>
            <%= link_to 'Dashboard',  root_path %>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="ri-menu-3-line"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
          </div>
          <ul class="navbar-list">
             <li>
                <a href="#" class="search-toggle iq-waves-effect d-flex align-items-center">
                   <%= image_tag "user/09.jpg", class:"img-fluid rounded mr-3"%>
                   <div class="caption">
                      <h6 class="mb-0 line-height"><%= current_user.full_name %></h6>
                      <% if patient_signed_in? %>
                        <span class="font-size-12">Profil pacjenta</span>
                      <% end %>
                      <% if doctor_signed_in? %>
                        <span class="font-size-12">Profil lekarza</span>
                      <% end %>
                   </div>
                </a>
                <div class="iq-sub-dropdown iq-user-dropdown">
                   <div class="iq-card shadow-none m-0">
                      <div class="iq-card-body p-0 ">
                         <div class="bg-primary p-3">
                            <span class="text-white font-size-12">Radiolog, Internista</span>
                         </div>
                         <a href="profile.html" class="iq-sub-card iq-bg-primary-hover">
                            <div class="media align-items-center">
                               <div class="rounded iq-card-icon iq-bg-primary">
                                  <i class="ri-file-user-line"></i>
                               </div>
                               <div class="media-body ml-3">
                                  <h6 class="mb-0 ">My Profile</h6>
                                  <p class="mb-0 font-size-12">Profile information</p>
                               </div>
                            </div>
                         </a>
                         <a href="privacy-setting.html" class="iq-sub-card iq-bg-primary-hover">
                            <div class="media align-items-center">
                               <div class="rounded iq-card-icon iq-bg-primary">
                                  <i class="ri-lock-line"></i>
                               </div>
                               <div class="media-body ml-3">
                                  <h6 class="mb-0 ">Account settings</h6>
                                  <p class="mb-0 font-size-12">Login and password</p>
                               </div>
                            </div>
                         </a>
                         <div class="d-inline-block w-100 text-center p-3">
                            <% if patient_signed_in? %>
                                <%= link_to('Wyloguj', destroy_patient_session_path, method: :delete, class: "bg-primary iq-sign-btn") %>
                            <% end %>
                            <% if doctor_signed_in? %>
                               <%= link_to('Wyloguj', destroy_doctor_session_path, method: :delete, class: "bg-primary iq-sign-btn") %>
                            <% end %>
                         </div>
                      </div>
                   </div>
                </div>
             </li>
          </ul>
       </nav>
    </div>
 </div>

app/views/solutions/new.html.erb
<h1>New Solution</h1>

<%= render 'form', solution: @solution %>

<%= link_to 'Back', solutions_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Pesel:</strong>
  <%= @user.pesel %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Pwz number:</strong>
  <%= @user.pwz_number %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @user.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @user.height %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>